### ISSUE TITLE
Facut chestionar pentru stabilire data

### ISSUE THREAD

**Issue by adiroiban** [softwareliber/flosscamp#1]
Cine trebuie sa faca un chestionar in care sa stabilim data.

Chestionarul trebuie sa aiba atatea optiuni cate weekenduri exista.

Nu trebuie puse campuri libere pentru data, pentru ca va fi greu de centralizat.

Formularul poate sa aiba si feedback cu sugestii pentru loc,

**Comment by doruilasi** [comment]
iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dElxYjZValhaVTM0TDAzaFVqVk5nUkE6MQ" width="760" height="1337" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe

link

**Comment by adiroiban** [comment]
Arata ok.

Putem sa il integram in site si sa il raspandim pe net.

Spor.
Adi

On 10 May 2012 18:47, Doru Ilasi
reply@reply.github.com
wrote:

> <iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dElxYjZValhaVTM0TDAzaFVqVk5nUkE6MQ" width="760" height="1337" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
> 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/softwareliber/flosscamp/issues/1#issuecomment-5628787

## 

Adi Roiban

**Comment by doruilasi** [comment]
Este integrat deja. Singura chestie care nu-mi @iese@ e sa schimb harta cu
cea noua :). Da o mana de ajutor acolo ca nu pricep de ce se incapataneaza
sa ramana cea veche.

Participantii vin acusa la tine si Stas rw pe drive, ro pe public .

On Thu, May 10, 2012 at 6:50 PM, Adi Roiban <
reply@reply.github.com

> wrote:
> 
> Arata ok.
> 
> Putem sa il integram in site si sa il raspandim pe net.
> 
> Spor.
> Adi
> 
> On 10 May 2012 18:47, Doru Ilasi
> reply@reply.github.com
> wrote:
> 
> > <iframe src="
> > https://docs.google.com/spreadsheet/embeddedform?formkey=dElxYjZValhaVTM0TDAzaFVqVk5nUkE6MQ"
> > width="760" height="1337" frameborder="0" marginheight="0"
> > marginwidth="0">Loading...</iframe>
> > 
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/softwareliber/flosscamp/issues/1#issuecomment-5628787
> 
> ## 
> 
> Adi Roiban
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/softwareliber/flosscamp/issues/1#issuecomment-5628852

## 

Doru Ilasi - Aplix
